# Golang CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    docker:
      # specify the version
      - image: circleci/golang:1.8
    steps:
      - checkout
      - persist_to_workspace:
          root: /go
          paths:
            - src


  deploy:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /go
      - run:
          name: Install and Run goreleaser
          command: curl -sL https://git.io/goreleaser | bash


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tag:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
